apiVersion: apps/v1
kind: Deployment
metadata:
  name: tnkrfun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tnkrfun
  template:
    metadata:
      labels:
        app: tnkrfun
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: web
        image: ghcr.io/dsmorgan/tnkrfun-site:sha-2c2b380
        ports:
        - containerPort: 80

